name = "ai-gateway"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

# KV namespace — wrangler will auto-resolve by name
[[kv_namespaces]]
binding = "KV"

# 管理员账号密码环境变量配置
[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123456"
# OPENCODE_MIRRORS_URL = "https://opencode.ai.cmliussss.net/zen/v1\nhttps://opencode.fastly.cmliussss.net/zen/v1\nhttps://opencode.gcore.cmliussss.net/zen/v1"
